### ISSUE TITLE
Demo on Codepen not working

### ISSUE THREAD

**Issue by RobotcomFA** [openplayerjs/openplayerjs-youtube#43]
Hi anybody,

I have demo code on Codepen but it is not working
https://codepen.io/rafa8626/pen/wvvOYpg

Can anyone help me?
Thanks

**Comment by rafa8626** [comment]
@RobotcomFA I fixed the package; after an upgrade in OpenPlayerJS, it was reaching for the wrong object to be initialized. Thanks for raising this issue; can you star both projects to show your support, please?

**Comment by RobotcomFA** [comment]
@rafa8626 

Thanks for your support

I had starred in both projects

**Comment by rafa8626** [comment]
Thanks @RobotcomFA
